### ISSUE TITLE
Add a saved stated

### ISSUE THREAD

**Issue by arnoldvantveld** [nens/batch-calculator#11]
Currently it is not yet possible to provide a saved state.

@woutlexmond Wat was ook alweer het probleem?

**Comment by woutlexmond** [comment]
The saved states are normally stored under this url: https://api.3di.live/v3.0/files/ which is currently not accessible because of a server error.

**Comment by woutlexmond** [comment]
Ik heb een nieuwe url toegevoegd aan de -help functie van de batch-calculator waar het wel mee zou moeten werken: help="The url of a timed saved state with id = [saved_state_id] belonging to a simulation with id = [sim_id] that will be used at the start of the simulation. Timed saved state urls should be provided in the following format: https://api.3di.live/v3.0/simulations/[sim_id]/create-saved-states/timed/[saved_state_id] Example: https://api.3di.live/v3.0/simulations/4719/create-saved-states/timed/1623/"
