### ISSUE TITLE
Make batch-calculator available for non-NenS users

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/batch-calculator#26]
### Inleiding
Nelen & Schuurmans Consultancy doet voor gemeenten regelmatig onderzoek naar het functioneren van het rioolstelsel (systeemoverzicht stedelijk water, SSW). Eén onderdeel van zo'n SSW is het "milieutechnisch functioneren". Hierbij wordt onderzocht hoeveel vuilwater er wordt overgestort door het systeem. Dit wordt gedaan volgens een vaste methode, vastgesteld door de branchevereniging Stichting Rioned. Deze methode houdt in dat er een serie buien uit de periode (volgens mij) 1955-1965 wordt losgelaten op het model, en dat de resultaten daarvan worden samengevat in een tabel. De tabel geeft per overstort de statistieken weer m.b.t. de hoeveelheid en de frequentie van overstorten.

Om dit met 3Di te kunnen doen, is er python scripting gemaakt (door @daanvaningen), in de repo `nens/batch-calculator`. Deze is momenteel alleen beschikbaar voor intern gebruik door Nelen & Schuurmans. De bedoeling is dat ook andere klanten hiervan gebruik kunnen gaan maken.

### Acties
- [x] De repo `batch-calculator` hernoemen naar `threedi-urban-eia-nl` (eia = environmental impact assessment)
- [x] De repo open source maken (controleren of de licentie open source is en zorgen dat ie publiek toegankelijk is)
- [ ] ~~De code compatible maken met de huidige versie van `chardet` (tenzij dit mega ingrijpend blijkt te zijn)~~
- [x] Een python package publiceren op pypi
- [x] Testen of de volgende workflow werkt (onder windows):
- Gebruiker installeert het pakketje met `pip install threedi-urban-eia-nl`
- Gebruiker runt roept vanaf de command line de utilities `run-rain-series-simulations` en `process-rain-series-results` aan. Voor de scope van dit ticket is het voldoende om te testen of het werkt om voor beide `--help` aan te roepen. Daarna zal het inhoudelijk verder worden getest

**Comment by elisalle** [comment]
@leendertvanwolfswinkel volgens mij wordt chardet überhaupt niet gebruikt in deze package; charset-normalizer wordt gebruikt. Op welke gebieden is de huidige versie van chardet incompatibel? Of wil je dat charset-normalizer wordt vervangen door chardet?

**Comment by leendertvanwolfswinkel** [comment]
@elisalle dat is omdat ik op de handleiding die onze consultants gebruiken het volgende zinnetje las: 

> Let op! Om de run-batch-calculator moet het python pakket chardet < 4.0.0. Met chardet 3.0.4 werkt de code wel.

Maar als jij zegt dat dit niet relevant is, dan lijkt het me niet nodig er iets mee te doen

**Comment by elisalle** [comment]
De interne werking van het pakket kan ik natuurlijk niet testen, maar iig de help commands doen het gewoon zonder chardet.
